SET SQL_SAFE_UPDATES = 0;

DELETE FROM Przystanki;
ALTER TABLE Przystanki AUTO_INCREMENT = 1;

DELETE FROM Rozklady;
ALTER TABLE Rozklady AUTO_INCREMENT = 1;

DELETE FROM Linie;
ALTER TABLE Linie AUTO_INCREMENT = 1;

DELETE FROM Biura;
ALTER TABLE Biura AUTO_INCREMENT = 1;

DELETE FROM Adresy;
ALTER TABLE Adresy AUTO_INCREMENT = 1;

DELETE FROM Poczty;
ALTER TABLE Poczty AUTO_INCREMENT = 1;

DELETE FROM Autobusy_T;
ALTER TABLE Autobusy_T AUTO_INCREMENT = 1;

DELETE FROM Tramwaje_T;
ALTER TABLE Tramwaje_T AUTO_INCREMENT = 1;

DELETE FROM Metra_T;
ALTER TABLE Metra_T AUTO_INCREMENT = 1;

DELETE FROM Pojazdy_T;
ALTER TABLE Pojazdy_T AUTO_INCREMENT = 1;

DELETE FROM Autobusy_modele;
ALTER TABLE Autobusy_modele AUTO_INCREMENT = 1;

DELETE FROM Tramwaje_modele;
ALTER TABLE Tramwaje_modele AUTO_INCREMENT = 1;

DELETE FROM Metra_modele;
ALTER TABLE Metra_modele AUTO_INCREMENT = 1;